# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pytest

on: [push]
jobs:
  Pytest:
    runs-on: ubuntu-latest
    name: Pytest
    steps:
      - name: Python Pytest Github Action
        uses: fylein/python-pytest-github-action@v2
